#![forbid(unsafe_code)]

pub mod input;
pub mod realtime;
pub mod screen_text;
mod standard_images;
mod standard_text;
pub mod verify_scenario;

pub use mdux_core::{
    DeterminismPolicy, DeviceContext, FrameworkIdentity, MduxResult, SafetyClass, ValidationError,
};
pub use mdux_governance::{
    AuditCategory, AuditEvent, ComplianceProgram, Hazard, ProblemReport, Requirement,
    RequirementId, TraceRow, VerificationCase, VerificationMethod,
};
pub use mdux_text_authoring::{
    DeterministicAtlasBuilder, FontFingerprint, RasterizedGlyph, TextCompilationInput,
    compile_text_package, fingerprint_font_file,
};
pub use mdux_text_runtime::{GlyphDrawCommand, TextRuntime};
pub use mdux_text_schema::{
    ApprovedString, AtlasGlyph, CompiledGlyph, CompiledTextRun, DeterminismEvidence, FontAsset,
    NumericGlyphEntry, NumericGlyphSet, NumericTemplate, TextDirection, TextPackage, TextureAtlas,
};
pub use mdux_image_schema::{ImageEvidence, ImagePackage};
pub use mdux_ml_authoring::{
    ArchitectureManifest as MlArchitectureManifest, ImportedWeights as MlImportedWeights,
    ModelCompilationInput as MlModelCompilationInput, WeightsFingerprint as MlWeightsFingerprint,
    compile_model_package, fingerprint_weights_file, generate_golden_vectors, import_safetensors,
    pipeline_description as ml_pipeline_description,
};
pub use mdux_ml_runtime::{Classifier1D, Prediction as MlPrediction};
pub use mdux_ml_schema::{
    DeterminismEvidence as MlDeterminismEvidence, Dtype as MlDtype, GoldenVector as MlGoldenVector,
    InputSpec as MlInputSpec, Layer as MlLayer, ModelPackage, OutputSpec as MlOutputSpec,
    Tensor as MlTensor,
};
pub use input::{DEFAULT_FRAME_EVENT_CAPACITY, FrameEvents, TextInputModel, WidgetEvent};
pub use standard_images::{
    ACME_LOGO, ACME_LOGO_IMAGE_ID, StandardImageDefinition, default_image_packages,
};
pub use mdux_ui::{
    ButtonSpec, ClockFormat, ClockSpec, CompiledNode, CompiledNodeKind, CompiledScreenPackage,
    CriticalButtonSpec, CvCheckKind, FrameStatistics, GoldenReferenceEntry, GraphicsProfile,
    ImageSpec, LabelSpec, LayoutKind, LayoutSpec, MedicalUiRuntime, NumericDisplaySpec,
    PanelSpec, PipelineMode, Rect, SignalTraceSpec, StatusIndicatorSpec, SystemEvent,
    THEME_COLORS, TextInputSpec, UiComponent, UiSdkConfig, ViewportReservation,
    resolve_color_token,
};
pub use standard_text::{
    DEFAULT_DISPLAY_DIGITS_GLYPH_SET_ID, DEFAULT_DISPLAY_FONT,
    DEFAULT_STANDARD_DIGITS_GLYPH_SET_ID, DEFAULT_STANDARD_FONT,
    DEFAULT_STANDARD_FONT_SOURCE_PATH, DEFAULT_STANDARD_HELLO_WORLD_RUN_ID,
    DEFAULT_STANDARD_HELLO_WORLD_STRING_ID, DEFAULT_STANDARD_HELLO_WORLD_TEXT,
    DISPLAY_160_DIGITS_GLYPH_SET_ID, ROBOTO_DISPLAY_400_48PX, ROBOTO_DISPLAY_400_160PX,
    ROBOTO_REGULAR_400_16PX, STANDARD_ASCII_TEXT_GLYPH_SET_ID, StandardFontDefinition,
    default_display_160_text_package, default_display_text_package,
    default_display_text_packages, default_standard_text_package,
};

/// Brings the module generated by [`mdux-build`](https://docs.rs/mdux-build)'s `MeduiScreen`
/// compiler into scope as `medui_screen`, exposing `medui_screen::screen()` and
/// `medui_screen::primary_text_node_id()`. Requires the calling crate's `build.rs` to have run
/// `mdux_build::MeduiScreen::new(..).surface(..).compile()`.
#[macro_export]
macro_rules! include_medui_screen {
    () => {
        pub mod medui_screen {
            include!(concat!(env!("OUT_DIR"), "/mdux_medui_screen.rs"));
        }
    };
}

/// Brings the module generated by [`mdux-build`](https://docs.rs/mdux-build)'s `ScenarioSet`
/// compiler into scope as `verify_scenarios`, exposing `verify_scenarios::SCENARIOS`. Requires
/// the calling crate's `build.rs` to have run
/// `mdux_build::ScenarioSet::new(..).compile()`.
#[macro_export]
macro_rules! include_scenarios {
    () => {
        pub mod verify_scenarios {
            include!(concat!(env!("OUT_DIR"), "/mdux_scenarios.rs"));
        }
    };
}

/// Brings the module generated by [`mdux-build`](https://docs.rs/mdux-build)'s `ModelPackage`
/// compiler into scope as `medui_model`, exposing `medui_model::model() -> mdux::ModelPackage`
/// (ADR-017). Requires the calling crate's `build.rs` to have run
/// `mdux_build::ModelPackage::new(..).compile()`. Swapping which committed
/// `generated/models/<id>/package.json` that build step points at — Hugging Face demonstrator
/// weights vs. a manufacturer's own clinically-qualified weights — changes zero application
/// source; this macro brings in whichever package was baked.
#[macro_export]
macro_rules! include_model {
    () => {
        pub mod medui_model {
            include!(concat!(env!("OUT_DIR"), "/mdux_ml_model.rs"));
        }
    };
}

pub struct FrameworkBuilder {
    device: Option<DeviceContext>,
    compliance: Option<ComplianceProgram>,
    ui_config: Option<UiSdkConfig>,
    ui_components: Vec<UiComponent>,
    screen: Option<&'static CompiledScreenPackage>,
    screen_locale: String,
}

impl FrameworkBuilder {
    pub fn new() -> Self {
        Self {
            device: None,
            compliance: None,
            ui_config: None,
            ui_components: Vec::new(),
            screen: None,
            screen_locale: "en-US".to_string(),
        }
    }

    pub fn with_device(mut self, device: DeviceContext) -> Self {
        self.device = Some(device);
        self
    }

    pub fn with_compliance(mut self, compliance: ComplianceProgram) -> Self {
        self.compliance = Some(compliance);
        self
    }

    pub fn with_ui(mut self, ui_config: UiSdkConfig) -> Self {
        self.ui_config = Some(ui_config);
        self
    }

    pub fn add_component(mut self, component: UiComponent) -> Self {
        self.ui_components.push(component);
        self
    }

    /// Derives a `UiComponent` for every node in `screen` whose kind exposes both a `text_key`
    /// and a `requirement_id` (currently every `CriticalButton`), resolving its label from the
    /// standard approved text package for `screen_locale` (default `en-US`, override with
    /// [`with_screen_locale`](Self::with_screen_locale)). Components derived this way are
    /// appended to any added via [`add_component`](Self::add_component).
    pub fn with_screen(mut self, screen: &'static CompiledScreenPackage) -> Self {
        self.screen = Some(screen);
        self
    }

    pub fn with_screen_locale(mut self, locale: impl Into<String>) -> Self {
        self.screen_locale = locale.into();
        self
    }

    pub fn build(mut self) -> MduxResult<Framework> {
        let device = self
            .device
            .ok_or_else(|| ValidationError::new("framework builder requires a device context"))?;
        let mut compliance = self.compliance.ok_or_else(|| {
            ValidationError::new("framework builder requires a compliance program")
        })?;
        let ui_config = self
            .ui_config
            .ok_or_else(|| ValidationError::new("framework builder requires a ui configuration"))?;

        if compliance.device() != &device {
            return Err(ValidationError::new(
                "device context and compliance program must describe the same software item",
            ));
        }

        compliance.validate()?;

        if device.safety_class == SafetyClass::C
            && ui_config.graphics_profile != GraphicsProfile::VulkanSc
        {
            return Err(ValidationError::new(
                "Class C devices must use the Vulkan SC graphics profile",
            ));
        }

        if let Some(screen) = self.screen {
            if self.screen_locale.trim().is_empty() {
                return Err(ValidationError::new(
                    "screen locale must not be empty or whitespace",
                ));
            }

            let text_package = default_standard_text_package()?;
            for node in screen.nodes {
                // Static requirement-bearing nodes (currently CriticalButton): label resolved
                // from the approved string the node renders.
                if let (Some(text_key), Some(requirement_id)) =
                    (node.kind.text_key(), node.kind.requirement_id())
                {
                    let label = text_package
                        .find_approved_string(text_key, &self.screen_locale)
                        .map(|approved_string| approved_string.value.clone())
                        .ok_or_else(|| {
                            ValidationError::new(format!(
                                "approved text package does not contain approved string {text_key} for locale {}",
                                self.screen_locale
                            ))
                        })?;
                    self.ui_components.push(UiComponent::new(
                        node.id,
                        label,
                        vec![RequirementId::new(requirement_id)?],
                    )?);
                    continue;
                }

                // Dynamic requirement-bearing nodes render varying content, so their traced
                // component uses a stable descriptive label instead of an approved string: the
                // node id for a numeric display or a text input, the first state's approved
                // label for a status indicator. (A requirement-bearing Button carries a static
                // approved label, so the dual-Some branch above already traced it.)
                match &node.kind {
                    CompiledNodeKind::TextInput(spec) => {
                        if let Some(requirement_id) = spec.requirement_id {
                            self.ui_components.push(UiComponent::new(
                                node.id,
                                node.id,
                                vec![RequirementId::new(requirement_id)?],
                            )?);
                        }
                    }
                    CompiledNodeKind::NumericDisplay(spec) => {
                        self.ui_components.push(UiComponent::new(
                            node.id,
                            node.id,
                            vec![RequirementId::new(spec.requirement_id)?],
                        )?);
                    }
                    CompiledNodeKind::StatusIndicator(spec) => {
                        let first_state_key = spec.state_text_keys.first().ok_or_else(|| {
                            ValidationError::new(format!(
                                "status indicator {} declares no states",
                                node.id
                            ))
                        })?;
                        let label = text_package
                            .find_approved_string(first_state_key, &self.screen_locale)
                            .map(|approved_string| approved_string.value.clone())
                            .ok_or_else(|| {
                                ValidationError::new(format!(
                                    "approved text package does not contain approved string {first_state_key} for locale {}",
                                    self.screen_locale
                                ))
                            })?;
                        self.ui_components.push(UiComponent::new(
                            node.id,
                            label,
                            vec![RequirementId::new(spec.requirement_id)?],
                        )?);
                    }
                    _ => {}
                }
            }
        }

        let mut seen_component_ids = std::collections::HashSet::with_capacity(self.ui_components.len());
        for component in &self.ui_components {
            if !seen_component_ids.insert(component.id.as_str()) {
                return Err(ValidationError::new(format!(
                    "duplicate ui component id {}",
                    component.id
                )));
            }

            for requirement_id in &component.requirement_ids {
                if !compliance.has_requirement(requirement_id) {
                    return Err(ValidationError::new(format!(
                        "ui component {} references unknown requirement {}",
                        component.id, requirement_id
                    )));
                }
            }
        }

        let ui = MedicalUiRuntime::new(ui_config, self.ui_components)?;

        compliance.record_event(
            AuditCategory::Release,
            format!("framework build completed for {}", device.software_item),
        );

        Ok(Framework {
            identity: FrameworkIdentity::default(),
            device,
            compliance,
            ui,
        })
    }
}

impl Default for FrameworkBuilder {
    fn default() -> Self {
        Self::new()
    }
}

pub struct Framework {
    identity: FrameworkIdentity,
    device: DeviceContext,
    compliance: ComplianceProgram,
    ui: MedicalUiRuntime,
}

impl Framework {
    pub fn identity(&self) -> &FrameworkIdentity {
        &self.identity
    }

    pub fn device(&self) -> &DeviceContext {
        &self.device
    }

    pub fn ui_runtime(&self) -> &MedicalUiRuntime {
        &self.ui
    }

    pub fn trace_matrix_export(&self) -> String {
        self.compliance.trace_matrix_export()
    }

    pub fn trace_rows(&self) -> Vec<TraceRow> {
        self.compliance.trace_rows()
    }

    pub fn audit_export(&self) -> String {
        self.compliance.audit_export()
    }

    pub fn release_summary(&self) -> String {
        format!(
            "framework={} version={} profile={} components={} {}",
            self.identity.name,
            self.identity.version,
            self.ui.config().profile_name(),
            self.ui.components().len(),
            self.compliance.release_evidence_summary()
        )
    }

    pub fn render_preview_frame(&self, frame_index: u64) -> FrameStatistics {
        self.ui.render_frame(frame_index)
    }

    /// Records a `Runtime`-category event on the compliance audit trail. The only
    /// post-`build()` mutation the facade exposes, introduced by ADR-013 so the presentation
    /// adapter can make host-preview executions self-documenting in the exported audit log.
    pub fn record_runtime_event(&mut self, message: impl Into<String>) {
        self.compliance
            .record_event(AuditCategory::Runtime, message);
    }
}
